version: '3.4'

networks:
  pethelp:
    driver: bridge

services:
  pethelpdb:
    container_name: pethelp-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=Password1234!
      - ACCEPT_EULA=Y
    networks:
      - pethelp
    ports:
      - 8003:1433
  pethelp:
    image: ${DOCKER_REGISTRY-}pethelp
    build:
      context: .
      dockerfile: PetHelp/Dockerfile
    networks:
      - pethelp
    ports: 
      - 8002:80
    environment:
      - DB_HOST=pethelpdb
      - DB_NAME=pethelp
      - DB_SA_PASSWORD=Password1234!
